### ISSUE TITLE
Tutorial Error

### ISSUE THREAD

**Issue by Robertooooooo** [BrancoLab/BrainRender#1] opened 2019-09-23 13:32 UTC
Dear Federico,

I am not a phyton expert..... I tried to run the BrainRender Tutorial but even when I change the main_fld directory I run in a error:

PermissionError                           Traceback (most recent call last)
<ipython-input-8-2d206b369cbe> in <module>
      1 # Let's create our first scene!
----> 2 tutorial_scene = Scene(jupyter=True)

~\Documents\Github\BrainRender\BrainRender\scene.py in __init__(self, brain_regions, regions_aba_color, neurons, tracts, add_root, verbose, jupyter, display_inset)
     68 
     69         """
---> 70         ABA.__init__(self)
     71         self.verbose = verbose
     72         self.regions_aba_color = regions_aba_color

~\Documents\Github\BrainRender\BrainRender\ABA_analyzer.py in __init__(self, projection_metric)
     43 
     44         # get mouse connectivity cache and structure tree
---> 45         self.mcc = MouseConnectivityCache(manifest_file=folders_paths['manifest'])
     46         self.structure_tree = self.mcc.get_structure_tree()
     47 

~\Anaconda3\lib\site-packages\allensdk\core\mouse_connectivity_cache.py in __init__(self, resolution, cache, manifest_file, ccf_version, base_uri, version)
    147         super(MouseConnectivityCache, self).__init__(
    148             resolution, reference_space_key=ccf_version, cache=cache,
--> 149             manifest=manifest_file, version=version)
    150 
    151         self.api = MouseConnectivityApi(base_uri=base_uri)

~\Anaconda3\lib\site-packages\allensdk\core\reference_space_cache.py in __init__(self, resolution, reference_space_key, **kwargs)
     68             kwargs['base_uri'] = None
     69 
---> 70         super(ReferenceSpaceCache, self).__init__(**kwargs)
     71 
     72         self.resolution = resolution

~\Anaconda3\lib\site-packages\allensdk\api\cache.py in __init__(self, manifest, cache, version, **kwargs)
     72                  **kwargs):
     73         self.cache = cache
---> 74         self.load_manifest(manifest, version)
     75 
     76     def get_cache_path(self, file_name, manifest_key, *args):

~\Anaconda3\lib\site-packages\allensdk\api\cache.py in load_manifest(self, file_name, version)
    114                 dirname = os.path.dirname(file_name)
    115                 if dirname:
--> 116                     Manifest.safe_mkdir(dirname)
    117 
    118                 self.build_manifest(file_name)

~\Anaconda3\lib\site-packages\allensdk\config\manifest.py in safe_mkdir(cls, directory)
    313         '''
    314         try:
--> 315             os.makedirs(directory)
    316         except OSError as e:
    317             if ((sys.platform == "darwin") and (e.errno == errno.EISDIR) and \

~\Anaconda3\lib\os.py in makedirs(name, mode, exist_ok)
    209     if head and tail and not path.exists(head):
    210         try:
--> 211             makedirs(head, exist_ok=exist_ok)
    212         except FileExistsError:
    213             # Defeats race condition when another thread created the path

~\Anaconda3\lib\os.py in makedirs(name, mode, exist_ok)
    209     if head and tail and not path.exists(head):
    210         try:
--> 211             makedirs(head, exist_ok=exist_ok)
    212         except FileExistsError:
    213             # Defeats race condition when another thread created the path

~\Anaconda3\lib\os.py in makedirs(name, mode, exist_ok)
    209     if head and tail and not path.exists(head):
    210         try:
--> 211             makedirs(head, exist_ok=exist_ok)
    212         except FileExistsError:
    213             # Defeats race condition when another thread created the path

~\Anaconda3\lib\os.py in makedirs(name, mode, exist_ok)
    209     if head and tail and not path.exists(head):
    210         try:
--> 211             makedirs(head, exist_ok=exist_ok)
    212         except FileExistsError:
    213             # Defeats race condition when another thread created the path

~\Anaconda3\lib\os.py in makedirs(name, mode, exist_ok)
    209     if head and tail and not path.exists(head):
    210         try:
--> 211             makedirs(head, exist_ok=exist_ok)
    212         except FileExistsError:
    213             # Defeats race condition when another thread created the path

~\Anaconda3\lib\os.py in makedirs(name, mode, exist_ok)
    219             return
    220     try:
--> 221         mkdir(name, mode)
    222     except OSError:
    223         # Cannot rely on checking for EEXIST, since the operating system

PermissionError: [WinError 5] Access is denied: '/Users/federicoclaudi'

**Comment by FedeClaudi** [comment] 2019-09-23 13:41
Hi, 

thank for trying BrainRender. As one of the first user I am afraid that you might bump into a few bugs that have escaped me so far. 

Just to make sure I get exactly what you tried: are you trying to run the Tutorial jupyter notebook correct?
And did you try editing 'main_fld' here (at the beginning of the tutorial):
![image](https://user-images.githubusercontent.com/17436313/65430430-d8854880-de0f-11e9-9637-3a59a729b88e.png)

or did you change it in `settings.py`? If you only changed in `settings.py` then the line above will put it back to it's original value (my path), which will give you an error. 

Also if you are using Windows make sure to specify the paths with two '\', the single '/' character is for  paths on mac. 

Let me know if this is of any help!

**Comment by Robertooooooo** [comment] 2019-09-23 14:48
yes I am running the Tutorial jupyter notebook and I am editing  'main_fld' directly in the notebook (on Windows).
I tried:

`main_fld = "C:/Users/Roberto/Desktop/temp"`
`main_fld = "/Users/Roberto/Desktop/temp"`
`main_fld = "//Users/Roberto/Desktop/temp`

but then I run in the error posted above

**Comment by FedeClaudi** [comment] 2019-09-23 14:59
Hi, 

On windows your path should look something like:
```main_fld = "C:\\Users\\Roberto\\Desktop\\temp"```

notice the use of double backslashes. 

Let me know if this work and what error message you get if it doesn't!

thank you

**Comment by Robertooooooo** [comment] 2019-09-23 15:20
Hi,

Still getting this:

`PermissionError                           Traceback (most recent call last)
<ipython-input-5-2d206b369cbe> in <module>
      1 # Let's create our first scene!
----> 2 tutorial_scene = Scene(jupyter=True)

~\Documents\Github\BrainRender\BrainRender\scene.py in __init__(self, brain_regions, regions_aba_color, neurons, tracts, add_root, verbose, jupyter, display_inset)
     68 
     69         """
---> 70         ABA.__init__(self)
     71         self.verbose = verbose
     72         self.regions_aba_color = regions_aba_color

~\Documents\Github\BrainRender\BrainRender\ABA_analyzer.py in __init__(self, projection_metric)
     43 
     44         # get mouse connectivity cache and structure tree
---> 45         self.mcc = MouseConnectivityCache(manifest_file=folders_paths['manifest'])
     46         self.structure_tree = self.mcc.get_structure_tree()
     47 

~\Anaconda3\lib\site-packages\allensdk\core\mouse_connectivity_cache.py in __init__(self, resolution, cache, manifest_file, ccf_version, base_uri, version)
    147         super(MouseConnectivityCache, self).__init__(
    148             resolution, reference_space_key=ccf_version, cache=cache,
--> 149             manifest=manifest_file, version=version)
    150 
    151         self.api = MouseConnectivityApi(base_uri=base_uri)

~\Anaconda3\lib\site-packages\allensdk\core\reference_space_cache.py in __init__(self, resolution, reference_space_key, **kwargs)
     68             kwargs['base_uri'] = None
     69 
---> 70         super(ReferenceSpaceCache, self).__init__(**kwargs)
     71 
     72         self.resolution = resolution

~\Anaconda3\lib\site-packages\allensdk\api\cache.py in __init__(self, manifest, cache, version, **kwargs)
     72                  **kwargs):
     73         self.cache = cache
---> 74         self.load_manifest(manifest, version)
     75 
     76     def get_cache_path(self, file_name, manifest_key, *args):

~\Anaconda3\lib\site-packages\allensdk\api\cache.py in load_manifest(self, file_name, version)
    114                 dirname = os.path.dirname(file_name)
    115                 if dirname:
--> 116                     Manifest.safe_mkdir(dirname)
    117 
    118                 self.build_manifest(file_name)

~\Anaconda3\lib\site-packages\allensdk\config\manifest.py in safe_mkdir(cls, directory)
    313         '''
    314         try:
--> 315             os.makedirs(directory)
    316         except OSError as e:
    317             if ((sys.platform == "darwin") and (e.errno == errno.EISDIR) and \

~\Anaconda3\lib\os.py in makedirs(name, mode, exist_ok)
    209     if head and tail and not path.exists(head):
    210         try:
--> 211             makedirs(head, exist_ok=exist_ok)
    212         except FileExistsError:
    213             # Defeats race condition when another thread created the path

~\Anaconda3\lib\os.py in makedirs(name, mode, exist_ok)
    209     if head and tail and not path.exists(head):
    210         try:
--> 211             makedirs(head, exist_ok=exist_ok)
    212         except FileExistsError:
    213             # Defeats race condition when another thread created the path

~\Anaconda3\lib\os.py in makedirs(name, mode, exist_ok)
    209     if head and tail and not path.exists(head):
    210         try:
--> 211             makedirs(head, exist_ok=exist_ok)
    212         except FileExistsError:
    213             # Defeats race condition when another thread created the path

~\Anaconda3\lib\os.py in makedirs(name, mode, exist_ok)
    209     if head and tail and not path.exists(head):
    210         try:
--> 211             makedirs(head, exist_ok=exist_ok)
    212         except FileExistsError:
    213             # Defeats race condition when another thread created the path

~\Anaconda3\lib\os.py in makedirs(name, mode, exist_ok)
    209     if head and tail and not path.exists(head):
    210         try:
--> 211             makedirs(head, exist_ok=exist_ok)
    212         except FileExistsError:
    213             # Defeats race condition when another thread created the path

~\Anaconda3\lib\os.py in makedirs(name, mode, exist_ok)
    219             return
    220     try:
--> 221         mkdir(name, mode)
    222     except OSError:
    223         # Cannot rely on checking for EEXIST, since the operating system

PermissionError: [WinError 5] Access is denied: '/Users/federicoclaudi'`

**Comment by FedeClaudi** [comment] 2019-09-23 15:31
I see, the fact that you get this at the end of your error message:
` PermissionError: [WinError 5] Access is denied: '/Users/federicoclaudi'  `

means that the path to main_fld hasn't changed from what is on the notebook. 
After you've changed main_fld in the notebook, did you run the cell where is defined again?

If you create a new cell and just write:
```print(folders_paths)```
and run it, what does it say?

**Comment by FedeClaudi** [comment] 2019-09-23 15:59
aha, found the problem. 

it should be 
``` folders_paths = update_folders(main_fld) ```
not
``` folder_paths = update_folders(main_fld) ```

there's a typo in the name of the variable so that it's not overwriting the old folder paths correctly. 
If you make this change it should work correctly. 

I've fixed the code so if you pull the latest commits it should be fixed. 

I will close this issue for now as the problem is solved, let me know if anything else goes wrong. 

Thank you

**Closed by FedeClaudi** 2019-09-23 15:59 UTC
Labels: bug
