### ISSUE TITLE
Repeat assignments to same scene variable make rendered graphic upside down

### ISSUE THREAD

**Issue by m-col** [BrancoLab/BrainRender#18] opened 2019-12-11 16:06 UTC
This is a weird bug, and I can't figure out why it is happening. If I want to loop over a few brain areas and create videos from each one, in theory I should be able to do this:

```
from BrainRender.scene import Scene
from BrainRender.Utils.videomaker import VideoMaker

regions = ['PRT', 'SCm', 'SCs']
for region in regions:
    scene = Scene()
    scene.add_brain_regions([region], colors='white', alpha=0.5)
    vm = VideoMaker(scene, savefile=f"Output/Videos/{region}.mp4", niters=120)
    vm.make_video(azimuth=3)
```

Indeed, this does create videos of these brain regions. However the second and third (and further videos if there are more regions) are rendered as upside down. I thought perhaps there is an object inside one of the imported files that is being manipulated at some point, but this wouldn't explain the observation that this script *does* work:

```
from BrainRender.scene import Scene
from BrainRender.Utils.videomaker import VideoMaker

scene1 = Scene()
scene1.add_brain_regions(['PRT'], colors='white', alpha=0.5)
vm1 = VideoMaker(scene1, savefile=f"Output/Videos/PRT.mp4", niters=120)
vm1.make_video(azimuth=3)

scene2 = Scene()
scene2.add_brain_regions(['SCm'], colors='white', alpha=0.5)
vm2 = VideoMaker(scene1, savefile=f"Output/Videos/SCm.mp4", niters=120)
vm2.make_video(azimuth=3)

scene3 = Scene()
scene3.add_brain_regions(['SCs'], colors='white', alpha=0.5)
vm3 = VideoMaker(scene1, savefile=f"Output/Videos/SCs.mp4", niters=120)
vm3.make_video(azimuth=3)
```

Ain't that weird? Are these two scripts not functionally equivalent? Am I being an idiot and missing something obvious?

**Comment by FedeClaudi** [comment] 2019-12-11 16:09
weird... you're creating a new instance of  `Scene` and `VideoMaker` at each iteration so it should all be reset to the default values.  I'll see if I can replicate it and what the cause might be..

**Comment by FedeClaudi** [comment] 2019-12-11 17:11
On my Mac, the first of the two examples has the same behaviour you described, the second yields an error:

```No fps was passed, using default: 30
No duration was passed, using default: 5
📽  Video PRT.mp4 is open...
Recalculated video FPS to 24.0
💾 Video saved as PRT.mp4
Could not retrieve data, possibly because there is no internet connection.
Rendering: (SCm)
No fps was passed, using default: 30
No duration was passed, using default: 5
📽  Video SCm.mp4 is open...
Traceback (most recent call last):
  File "/Users/federicoclaudi/Documents/Github/BrainRender/User/test.py", line 27, in <module>
    vm2.make_video(azimuth=3)
  File "./BrainRender/Utils/videomaker.py", line 76, in make_video
  File "/Users/federicoclaudi/miniconda3/envs/brainrender/lib/python3.7/site-packages/vtkplotter/plotter.py", line 1499, in show
    addons.addAxes()
  File "/Users/federicoclaudi/miniconda3/envs/brainrender/lib/python3.7/site-packages/vtkplotter/addons.py", line 776, in addAxes
    r = vp.renderers.index(vp.renderer)
ValueError: None is not in list
```

This second error seems to be a vtkplotter problem rather than brain render. But it means that something different must be happening between the two experiments, I have no idea what though. 


In general the video feature could really do with some improvements. It's not very flexible or accurate at all currently.

**Comment by m-col** [comment] 2019-12-11 18:00
Could the `Could not retrieve data, possibly because there is no internet connection` error be indicating that the data is empty, thereby causing the resultant `ValueError: None is not in list` error?

**Comment by FedeClaudi** [comment] 2019-12-11 22:18
No that shouldn't be the cause. I can run the 4 videos with the loop, and with an internet connection I get the same error.

The problem seems to be that in your example code when you call VideoMaker the second time you pass it scene1 as argument:
`vm2 = VideoMaker(scene1, savefile=f"Output/Videos/SCm.mp4", niters=120)`

Using scene2 the error doesn't  come up anymore and the behaviour is the same as in the loop. 

I will look into this.

**Comment by FedeClaudi** [comment] 2019-12-11 23:07
This should've been fixed with: 02b72aebd76ee237ffa8c95ab61e03f5efdb6d2d

The problem seem to be with vtkplotter, once an instance of the plotter has been created, actors are upside down for the following plotters (even if these should be completely independent objects).

The quick and dirty solution is to check if the current scene's plotter is not the first being created, and then rotate the actors accordingly:

<img width="332" alt="image" src="https://user-images.githubusercontent.com/17436313/70668188-cd9dbf80-1c6a-11ea-96b8-b105cf3daf7c.png">

But this might be very slow for scenes with complicated renderings (e.g. streamlines or morphologies). 

I will get in touch with Marco Musy from vtkplotter to see if he has any advice.

**Comment by m-col** [comment] 2019-12-12 10:59
OK so I'm only partly an idiot. Pretty strange behaviour on vtkplotter's part, that deleting an instance doesn't propagate to its internal copies, though there could be a good reason for this.

The workaround seems fine.

**Comment by marcomusy** [comment] 2019-12-12 15:27
Hi, 
interesting... one possibility is that by simply creating a new `Plotter` instance is not clearing the internal list of created objects, which is a global variable, and that's what's picked up by subsequent scenes.
What happens if you close the scene with `Scene.closePlotter()`?

**Comment by FedeClaudi** [comment] 2019-12-12 15:41
Hi, 

I've tried doing `scene.plotter.Close()` and `scene.plotter.closeWindow()` as well as `del scene.plotter` and removing the plotter instance from the global variable holding all plotters instances, but non of these changed the behaviour.

**Comment by marcomusy** [comment] 2019-12-12 17:00
Oh that's pretty weird.. I'll try and see if I can reproduce the issue with the Plotter class.

**Comment by marcomusy** [comment] 2020-01-08 20:06
Hi Federico, you might try to check if the problem is still there in the latest release (i guess it will..), plus there are a few deprecated methods which may get in the way..
Let me know if you encounter any problems

**Comment by FedeClaudi** [comment] 2020-01-08 22:25
Hi Marco,

I've update vtkplotter but the problem is still there. Running this minimal example reproduces the bug:

```
from brainrender.scene import Scene

regions = ['PRT', 'SCm', 'SCs']
for region in regions:
    scene = Scene()
    scene.add_brain_regions([region], colors='white', alpha=0.5)
    scene.render()
```

The only way to avoid this is to add to `scene.render()` this:
```
if len(vtkplotter.settings.plotter_instances) > 1:
    self._rotate_actors()
```
to rotate all actors in the scene if there are other `plotter_instances`.

**Comment by marcomusy** [comment] 2020-01-09 11:19
I just pulled the git repo but I get this error message:
`ModuleNotFoundError: No module named 'brainrender'`
i guess it's some mismatch with capital letters in the module name..

**Comment by FedeClaudi** [comment] 2020-01-09 13:27
mmm that's weird, it works for me. 
I'll look into it, but in the meanwhile if you `pip install brainrender` you should be able to run the code above.

**Comment by marcomusy** [comment] 2020-01-13 17:34
Hi Federico, 
sorry for the delay in addressing this issue. I just tried the above code with the master version of brainrender (which now works from master) and I get this sequence of outputs:
![p1](https://user-images.githubusercontent.com/32848391/72277792-df400180-3632-11ea-8eea-6b6ffde495cd.png)
![p2](https://user-images.githubusercontent.com/32848391/72277793-df400180-3632-11ea-89e0-830dd5bb4407.png)
![p3](https://user-images.githubusercontent.com/32848391/72277795-dfd89800-3632-11ea-97fe-b92f685889da.png)

So i'm not sure if the problem is still there or you managed to fixed it ..or if it's my local version of vtkplotter which now works ok..

**Comment by FedeClaudi** [comment] 2020-01-13 22:59
Hi,

thanks for looking into this. 

As far as I can tell vtkplotter is still inverting the actors for the second and third scene.
To correct for this, in brainrender I rotate the actors before rendering the scene. Within the 
`Scene.render()` I check if other plotter instances exist, and if they do I rotate the actors (thus correcting the rotation due to vtkplotter:
```
if len(vtkplotter.settings.plotter_instances) > 1:
    self._rotate_actors()
```

As far as I am concerned this solution is okay for brainrender. It might slow rendering for complicated scenes, but I don't think that it's an issue that is going to come up frequently.
I thought I'd let you know anyways so that you can look into what in vtkplotter is causing this if you want to. 

Cheers, 
Federico

**Closed** 2020-01-20 08:54 UTC
Labels: bug
